### PR TITLE
[Not Ready/Require Help] - Swift 4 Update

### PR DESCRIPTION
**Pull request by startupthekid**
### Added
- Integrated fastlane to automate the build process
- Added swiftlint fastlane task
- lint script to run in xcode build phase

### Changed
- updated travis config file
- updated podspec

### Remaining

- Fix the tests: I'm not really familiar with the Cleanse API but the tests don't compile for one of two reasons:
1. the `build` function is missing the seed parameter
2. ambiguous use of `bind`

- Is the Makefile used at all? I fixed the `clean` task (from `swift build --clean` to `swift package clean`. I also changed the build step from:

```
generated_sources: Cleanse/BinderArities.swift Cleanse/PropertyInjectionArities.swift

Cleanse/BinderArities.swift: CleanseGen/GenerateBinderArities.swift
	xcrun swift CleanseGen/GenerateBinderArities.swift > Cleanse/BinderArities.swift

Cleanse/PropertyInjectionArities.swift: CleanseGen/GeneratePropertyInjectionArities.swift
	xcrun swift CleanseGen/GeneratePropertyInjectionArities.swift > Cleanse/PropertyInjectionArities.swift
```

to this:

```
generated_sources: Cleanse/BinderArities.swift Cleanse/PropertyInjectionArities.swift

Cleanse/BinderArities.swift: CleanseGen/main.swift
	xcrun swift CleanseGen/main.swift > Cleanse/BinderArities.swift

Cleanse/PropertyInjectionArities.swift: CleanseGen/main.swift
	xcrun swift CleanseGen/main.swift > Cleanse/PropertyInjectionArities.swift
```

and that seems to work? But I'm not sure.

Additionally: where is sphinx being installed? (assuming its referring to this: http://www.sphinx-doc.org/en/stable/tutorial.html)
Same question for jazzy, there's nothing in the Gemfile to install it and when I added it the the Gemfile, `bundle install` is failing.

### CODE REVIEW

**Comment by holmes** [comment]
Thanks @startupthekid!

@mikelikespie and I will take a look and hopefully get this merged ASAP!

**Comment by holmes** [comment]
Can we break this up into some smaller PRs? One for linting/code formatting, another adding fastlane and another to make the changes for Swift 4? 

This has gotten rather large and is a bit hard to reason about.

**Comment by startupthekid** [comment]
Yes indeed!

**Comment by akinsete** [comment]
How can I contribute to making this library suppose Swift 4?

**Comment by holmes** [comment]
@akinsete I'm hoping @startupthekid can break up his PR into more digestable chunks. You might want to takea stab at it if we don't see any updates soon.

**Comment by startupthekid** [comment]
@akinsete @holmes the Swift 4 conversion wasn't an issue, that only took about ten minutes. Much harder and more time consuming is updating the tests (they don't even build right now), getting the Makefile to run all tasks successfully (also doesn't work), and setup CI builds for this project. There is a .travis.yml but nothing is hooked up as of yet.

I also ran into so much trouble installing the gems but that may just be my current setup.

**Comment by startupthekid** [comment]
@holmes could you enable Travis CI for the project? I don't think I can since I'm not a maintainer. Let's get some CI running on this thing 👍

**Comment by startupthekid** [comment]
Also quick question @holmes: #59 mentions you fixed the library call sites, are there updated tests as well? I think they're suffering from the same compilation errors that originally broke in swift 3.2. If you have tests you guys run internally at Square that work, that'd be a huge help

**Comment by startupthekid** [comment]
@holmes any thoughts on the above?

**Comment by holmes** [comment]
Sorry for the delay @startupthekid. We don't have any internal tests, everything is out here on github. We're going to spend some time this week and make sure we can get this updated and working.

**Comment by startupthekid** [comment]
Awesome! How can I help? Would this week be a good time for to split up all the PRs or should I wait until you guys finish your stuff?

**Comment by holmes** [comment]
I think now would be a good time to split up the PRs. We should be able to
leverage a lot of what you’ve done.

**Comment by startupthekid** [comment]
@holmes great! I'll start to tackle that this weekend!

**Comment by holmes** [comment]
Swift 4 updates have been merged. We've still got to work on updating docs and everything else.

**Comment by startupthekid** [comment]
I'll close this PR then. What's the branch I should point stuff to?

**Comment by holmes** [comment]
We merged the swift 4 changes to master, so feel free to target that branch. We'll cut a tag when we update docs.

**Pull request closed without merging**
