### PR TITLE
Better use of Void closures

### PR DESCRIPTION
**Pull request by abdullahselek**
- With this pull request use of void closures have better syntax standards.

### CODE REVIEW

**Comment by holmes** [comment]
Can you update `CleanseGen/GeneratePropertyInjectionArities.swift` and the playground and Examples?

**Comment by abdullahselek** [comment]
@holmes I added new commits according to `CleanseGen/GeneratePropertyInjectionArities.swift` and examples, I saw that there is no need to update playgrounds they are already good.

**Comment by holmes** [comment]
Thanks @abdullahselek! 

I'll release a new RC w/ this shortly

**Comment by abdullahselek** [comment]
Thanks @holmes

**Pull request merged**
