### PR TITLE
Swift4 Support.

### PR DESCRIPTION
**Pull request by sebastianv1**
Due to SE-0110, all of the binder arity functions become ambiguous with arity-1 and arity-0 to the swift compiler. As a solution in order to unblock using Cleanse with Swift4, renaming just these two functions to include their arity count (`to0` and `to1`) minimizes the surface area of the public API that requires modification. This also makes it much easier to revert back to simply using `to` when the issue is resolved in Swift.

Something else worth noting is that you will receive a runtime error (missing binding) if you use the incorrect function name for `to0` or `to1`.

### CODE REVIEW

**Comment by sebastianv1** [comment]
This resolves issue #67 @mikelikespie @holmes

**Comment by holmes** [comment]
`to1` vs `to1` is a runtime error? Does it fail when validating the graph or when it's actually used?

**Comment by holmes** [comment]
Changes look good. We should see what we can do to make the failure appear during graph validation if it's the case where it fails only when called.

**Comment by sebastianv1** [comment]
@holmes It fails at validation. The problem would occur when one uses `to0` incorrectly with implicit factory functions (i.e. `Root.init that has 1 dependency) when `to1` should be used.

**Comment by jrmay** [comment]
I would have a preference for `toArity0`, `toArity1`, etc. here to indicate what the numbers refer to. 

I'm fine with this for now, but I would also like to investigate a less ugly long term solution. We could pass type list to `to:` function before closure, removing the need to infer closure arity.

If we take this approach, do we want to bump the major version here to indicate API-breaking change?

**Comment by sebastianv1** [comment]
@jrmay The less ugly long term solution is ideally back to the old API where we don't have to use `to1` and `to0` and just `to`.

Yeah I was gonna push a tag and update the README with this change.

**Comment by holmes** [comment]
Thanks @sebastianv1!

**Pull request merged**
